name: Deploy to cPanel

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Upload via FTP
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: ${{ secrets.FTP_SERVER_MPDEV }}
                  username: ${{ secrets.FTP_USERNAME_MPDEV }}
                  password: ${{ secrets.FTP_PASSWORD_MPDEV }}
                  protocol: ftp
                  port: 21
                  local-dir: ./
                  server-dir: public_html/dev-test/wp-content/plugins/marketing-planet-plugin/

    # Automotivaters
    deploy_am:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Upload via FTP
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: ${{ secrets.FTP_SERVER_AM }}
                  username: ${{ secrets.FTP_USERNAME_AM }}
                  password: ${{ secrets.FTP_PASSWORD_AM }}
                  protocol: ftp
                  port: 21
                  local-dir: ./
                  server-dir: public_html/wp-content/plugins/marketing-planet-plugin/

    # Yaletown Dental
    deploy_yd:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Upload via FTP
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: ${{ secrets.FTP_SERVER_YD }}
                  username: ${{ secrets.FTP_USERNAME_YD }}
                  password: ${{ secrets.FTP_PASSWORD_YD }}
                  port: 21
                  local-dir: ./
                  server-dir: /public_html/wp-content/plugins/marketing-planet-plugin/
